version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: matheus/node_crud_app
    ports:
      - "3001:3001"
    environment:
      - PG_DB=node_crud_app_db
      - PG_USER=matheus
      - PG_PASSWORD=matheus
      - PG_HOST=node_db
    depends_on:
      - node_db
    restart: always

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=node_crud_app_db
      - POSTGRES_USER=matheus
      - POSTGRES_PASSWORD=matheus
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}